### ISSUE TITLE
Not compatible with the most recent version of html5lib

### ISSUE THREAD

**Issue by Chronial** [divio/djangocms-text-ckeditor#345] opened 2016-08-08 01:33 UTC
Fails with the most recent version of html5lib (`0.999999999`) with this exception:

```
  File ".../python3.4/site-packages/djangocms_text_ckeditor/html.py", line 8, in <module>
    from html5lib import sanitizer, serializer, treebuilders, treewalkers
```

This is probably caused by this change (from htlm5lib changelog): 

> Get rid of the sanitizer package. Merge sanitizer.sanitize into the sanitizer.htmlsanitizer module and move that to saniziter. This means anyone who used sanitizer.sanitize or sanitizer.HTMLSanitizer needs no code changes.

**Comment by czpython** [comment] 2016-08-08 11:17
Thanks for reporting.
Closing as a duplicate of https://github.com/divio/djangocms-text-ckeditor/issues/336
djangocms-text-ckeditor currently pins html5lib to be less than 0.999999999

**Closed by czpython** 2016-08-08 11:17 UTC

**Comment by Chronial** [comment] 2016-08-08 12:00
Ah, thx – I actually checked that, but was fooled by the [requirements.txt](https://github.com/divio/djangocms-text-ckeditor/blob/master/requirements.txt#L2) :).

I will see if I can produce a PR for the actual issue – our project needs a more recent version of html5lib.

**Comment by czpython** [comment] 2016-08-08 12:45
@Chronial That would be amazing :)
