### ISSUE TITLE
Using the language template variable in settings.py does not work

### ISSUE THREAD

**Issue by furiousdave** [divio/djangocms-text-ckeditor#229] opened 2015-03-06 17:32 UTC
It appears that when language is set to use a template variable in settings.py, as demonstrated in the readme:

CKEDITOR_SETTINGS = {
    'language': '{{ language }}',
    ...

that this string just gets escaped and printed out in the rendered template.

Confirm by viewing the page source of the edit-plugin view, /admin/cms/page/edit-plugin/xxx, and checking out the ckeditor init.

Here's mine:
CMS.CKEditor.init(container, {"toolbar_CMS": [["Format"], ["Bold", "Italic", "Underline"], ["Superscript", "Subscript", "SpecialChar"], ["JustifyLeft", "JustifyCenter", "JustifyRight"], ["NumberedList", "BulletedList"], ["Indent", "Outdent"], ["HorizontalRule"], ["Undo", "Redo"], "/", ["cmsplugins"], ["Image"], ["Find", "Replace"], ["Scayt"], ["Paste", "PasteText", "PasteFromWord", "RemoveFormat"], ["Link", "Unlink", "Anchor"], ["Table"], ["Language", "Templates"], ["Source"]], "language_list": ["en:English", "fr:French", "es:Spanish", "ru:Russian", "ar-sa:Arabic:rtl"], "toolbar": "CMS", "language": "{{ language }}", "height": "400"}

**Comment by yakky** [comment] 2015-03-07 22:47
I can't reproduce on a basic django CMS setup.

You can test this on a minimal project:

    git clone https://github.com/divio/djangocms-text-ckeditor.git
    cd djangocms-text-ckeditor
    virtualenv env
    . env/bin/activate
    pip install -r requirements-tests.txt
    djangocms-helper djangocms_text_ckeditor server --cms --extra-settings=test_settings

This will create a minimal test website to interact with
Go to http://localhost:8000, create a page and check the corresponding plugin settings

**Comment by furiousdave** [comment] 2015-03-09 20:15
Ah interesting. Checked one of my other projects and it does work there as well. Now to double check versions/look for conflicts in the project. Thank you for testing.

**Comment by yakky** [comment] 2015-04-18 12:58
Closing this

**Closed by yakky** 2015-04-18 12:58 UTC
