### ISSUE TITLE
html5lib version 0.999999999 (latest) does not work with djangocms-text-ckeditor

### ISSUE THREAD

**Issue by JoeJasinski** [divio/djangocms-text-ckeditor#344] opened 2016-08-06 03:11 UTC
If I install the latest version of html5lib, I get the following import error when I try to migrate.  I'm using djangocms-text-ckeditor==3.0.1 and djangocms==3.3.1. 

When I downgrade to html5lib==0.9999999, it works. 

```
(myproject)$ ./manage.py migrate 
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "Sites/myproject/envs/myproject/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "Sites/myproject/envs/myproject/lib/python2.7/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "Sites/myproject/envs/myproject/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "Sites/myproject/envs/myproject/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "Sites/myproject/envs/myproject/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Sites/myproject/proj/myproject/myproject/apps/pagefeature/models.py", line 8, in <module>
    from djangocms_text_ckeditor.fields import HTMLField
  File "/Sites/myproject/envs/myproject/lib/python2.7/site-packages/djangocms_text_ckeditor/fields.py", line 9, in <module>
    from .html import clean_html
  File "/Sites/myproject/envs/myproject/lib/python2.7/site-packages/djangocms_text_ckeditor/html.py", line 8, in <module>
    from html5lib import sanitizer, serializer, treebuilders, treewalkers
ImportError: cannot import name sanitizer
```

**Comment by JoeJasinski** [comment] 2016-08-06 03:50
I think this might be related to the following:

https://github.com/html5lib/html5lib-python/issues/72
https://github.com/html5lib/html5lib-python/issues/277

**Comment by czpython** [comment] 2016-08-06 14:19
Closing as a duplicate of https://github.com/divio/djangocms-text-ckeditor/issues/336
djangocms-text-ckeditor currently pins html5lib to be less than 0.999999999

**Closed by czpython** 2016-08-06 14:19 UTC
