### ISSUE TITLE
ValueError due to static file resolution on import time

### ISSUE THREAD

**Issue by stefanw** [divio/djangocms-text-ckeditor#476] opened 2018-04-16 17:18 UTC
[These lines](https://github.com/divio/djangocms-text-ckeditor/blob/d398fa0bbf823b8738ee909f2ede811869ca2747/djangocms_text_ckeditor/widgets.py#L22-L26) cause static file resolution on import time. Unfortunately, the module is imported on app register (through model -> fields -> widgets).

This usually works fine, but with staticfiles storage set to [`ManifestStaticFilesStorage`](https://docs.djangoproject.com/en/2.0/ref/contrib/staticfiles/#django.contrib.staticfiles.storage.ManifestStaticFilesStorage) it will cause an error when the file is not in the manifest. Adding it to the manifest via `collectstatic` does not work as it causes the same error.

Resolving static files during import time seems generally not to be a good idea. Lazy evaluation via [a media property](https://docs.djangoproject.com/en/2.0/topics/forms/media/#dynamic-property) instead of an inner Media class should fix this.

**Comment by czpython** [comment] 2018-04-16 17:33
Closing as duplicate of https://github.com/divio/djangocms-text-ckeditor/issues/474

**Closed by czpython** 2018-04-16 17:33 UTC
